name: Install

on:
 push:
  branches: [ master ]
 workflow_dispatch:

# remove the following line to run
# if: ${{ false }}

jobs:

# install --------------------------------------------------------------
 install:
  name: Installers
  runs-on: ubuntu-latest
  steps:
   - name: Checkout Git repository
     uses: actions/checkout@v4

   - name: Build
     run: |
      sudo apt-get install -y dos2unix
      script/build.sh

   - name: Release
     uses: ncipollo/release-action@v1
     with:
      tag: build
      artifacts: "fbsd64.tar.gz,linux64.tar.gz,mac64.zip,obsd64.tar.gz,raspi32.tar.gz,raspi64.tar.gz,win64.zip,winarm64.zip,build.txt,revision.txt"
      token: ${{ secrets.GITHUB_TOKEN }}
      allowUpdates: true
      replacesArtifacts: true

# windows AIO ----------------------------------------------------------
 winaio:
  if: ${{ false }}
  name: WinAIO
  runs-on: windows-latest
  needs: install
  steps:
   - name: Checkout Git repository
     uses: actions/checkout@v4
     env:
        password: ${{ secrets.PASSWORD }}
        url: https://github.com/${{github.repository}}

   - name: Get revision
     uses: dsaltares/fetch-gh-release-asset@master
     with:
      file: 'revision.txt'
      target: 'revision.txt'
      token: ${{ secrets.GITHUB_TOKEN }}

   - name: Get winzip
     uses: dsaltares/fetch-gh-release-asset@master
     with:
      file: 'win64.zip'
      target: 'win64.zip'
      token: ${{ secrets.GITHUB_TOKEN }}

   - name: List
     shell: pwsh
     run: dir

   - name: Get version
     shell: pwsh
     run: script\getversion.ps1

   - name: Get files
     shell: pwsh
     run: script\getfiles.ps1 0 0

   - name: Build AIO
     uses: joncloud/makensis-action@v4

   - name: Rename build
     shell: pwsh
     run: script\rename.ps1 0

   - name: Release WinAIO
     uses: ncipollo/release-action@v1
     with:
      tag: build
      artifacts: win64.exe
      token: ${{ secrets.GITHUB_TOKEN }}
      allowUpdates: true
      replacesArtifacts: true

# windows slim AIO -----------------------------------------------------
 winaios:
  if: ${{ false }}
  name: WinAIOslim
  runs-on: windows-latest
  needs: install
  steps:
   - name: Checkout Git repository
     uses: actions/checkout@v4
     env:
        password: ${{ secrets.PASSWORD }}
        url: https://github.com/${{github.repository}}

   - name: Get revision
     uses: dsaltares/fetch-gh-release-asset@master
     with:
      file: 'revision.txt'
      target: 'revision.txt'
      token: ${{ secrets.GITHUB_TOKEN }}

   - name: Get winzip
     uses: dsaltares/fetch-gh-release-asset@master
     with:
      file: 'win64.zip'
      target: 'win64.zip'
      token: ${{ secrets.GITHUB_TOKEN }}

   - name: List
     shell: pwsh
     run: dir

   - name: Get version
     shell: pwsh
     run: script\getversion.ps1

   - name: Get files
     shell: pwsh
     run: script\getfiles.ps1 1 0

   - name: Build AIO
     uses: joncloud/makensis-action@v4

   - name: Rename build
     shell: pwsh
     run: script\rename.ps1 0

   - name: Release WinAIO
     uses: ncipollo/release-action@v1
     with:
      tag: build
      artifacts: win64_slim.exe
      token: ${{ secrets.GITHUB_TOKEN }}
      allowUpdates: true
      replacesArtifacts: true

# windows arm slim AIO -----------------------------------------------------
 winarmaios:
  name: WinarmAIOslim
  runs-on: windows-latest
  needs: install
  steps:
   - name: Checkout Git repository
     uses: actions/checkout@v4
     env:
        password: ${{ secrets.PASSWORD }}
        url: https://github.com/${{github.repository}}

   - name: Get revision
     uses: dsaltares/fetch-gh-release-asset@master
     with:
      file: 'revision.txt'
      target: 'revision.txt'
      token: ${{ secrets.GITHUB_TOKEN }}

   - name: Get winzip
     uses: dsaltares/fetch-gh-release-asset@master
     with:
      file: 'winarm64.zip'
      target: 'winarm64.zip'
      token: ${{ secrets.GITHUB_TOKEN }}

   - name: List
     shell: pwsh
     run: dir

   - name: Get version
     shell: pwsh
     run: script\getversion.ps1

   - name: Get files
     shell: pwsh
     run: script\getfiles.ps1 1 1

   - name: Build AIO
     uses: joncloud/makensis-action@v4

   - name: Rename build
     shell: pwsh
     run: script\rename.ps1 0

   - name: Release WinarmAIO
     uses: ncipollo/release-action@v1
     with:
      tag: build
      artifacts: winarm64_slim.exe
      token: ${{ secrets.GITHUB_TOKEN }}
      allowUpdates: true
      replacesArtifacts: true

# webhook --------------------------------------------------------------
 webhook:
  if: ${{ false }}
  name: Run Webhook
  runs-on: ubuntu-latest
  needs: [winaio, winaios, winarmaios]
  steps:
   - name: distribution
     uses: distributhor/workflow-webhook@v2
     env:
      webhook_url: ${{ secrets.WEBHOOK_URL }}
      webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
      data: '{ "id": "jinstall" }'
